export const cities = {
  Albuquerque: "albuquerque",
  Anchorage: "anchorage",
  Asheville: "asheville",
  Atlanta: "atlanta",
  Austin: "austin",
  "Birmingham, AL": "birmingham-al",
  Boise: "boise",
  Boston: "boston",
  Boulder: "boulder",
  Bozeman: "bozeman",
  Brighton: "brighton",
  Buffalo: "buffalo",
  Charleston: "charleston",
  Charlotte: "charlotte",
  Chattanooga: "chattanooga",
  Chicago: "chicago",
  Cincinnati: "cincinnati",
  Cleveland: "cleveland",
  "Colorado Springs": "colorado-springs",
  Columbus: "columbus",
  Dallas: "dallas",
  Denver: "denver",
  "Des Moines": "des-moines",
  Detroit: "detroit",
  Eugene: "eugene",
  "Fort Collins": "fort-collins",
  Honolulu: "honolulu",
  Houston: "houston",
  Indianapolis: "indianapolis",
  Jacksonville: "jacksonville",
  "Kansas City": "kansas-city",
  Knoxville: "knoxville",
  "Las Vegas": "las-vegas",
  "Los Angeles": "los-angeles",
  Louisville: "louisville",
  Madison: "madison",
  Memphis: "memphis",
  Miami: "miami",
  Milwaukee: "milwaukee",
  "Minneapolis-Saint Paul": "minneapolis-saint-paul",
  Nashville: "nashville",
  "New Orleans": "new-orleans",
  "New York": "new-york",
  "Oklahoma City": "oklahoma-city",
  Omaha: "omaha",
  Orlando: "orlando",
  "Palo Alto": "palo-alto",
  Philadelphia: "philadelphia",
  Phoenix: "phoenix",
  Pittsburgh: "pittsburgh",
  "Portland, ME": "portland-me",
  "Portland, OR": "portland-or",
  Raleigh: "raleigh",
  Richmond: "richmond",
  Rochester: "rochester",
  "Salt Lake City": "salt-lake-city",
  "San Antonio": "san-antonio",
  "San Diego": "san-diego",
  "San Francisco Bay Area": "san-francisco-bay-area",
  "San Jose": "san-jose",
  "San Juan": "san-juan",
  "San Luis Obispo": "san-luis-obispo",
  Seattle: "seattle",
  "St. Louis": "st-louis",
  "Tampa Bay Area": "tampa-bay-area",
  Toulouse: "toulouse",
  "Washington, D.C.": "washington-dc",
};

export const cityUIds = Object.keys(cities).map(city => {
    return cities[city];
  })
